### ISSUE TITLE
Bad `umd2esm` plugin in `build.js` script

### ISSUE THREAD

**Issue by arthur-fontaine** [volarjs/language-tools-starter#4]
**Description**

https://github.com/volarjs/starter/blob/45c67d825ab1aff27390078098a1ceb7a275f6a3/packages/vscode/scripts/build.js#L22-L27

The code above will convert `umd` imports to `esm` by replacing "umd" with "esm" in the filepath.

However, the path generated no longer work for `vscode-uri` as of 3.0.8.
The path for `umd` import is `"lib/umd/index.js"`, but the path for `esm` import is `"lib/esm/index.mjs"`. As the script replaces `"lib/umd/index.js"` with `"lib/esm/index.js"`, esbuild fails to resolve the `esm` import.

> Reference to the commit that changes the export path for `esm`: https://github.com/microsoft/vscode-uri/commit/53e4ca6263f2e4ddc35f5360c62bc1b1d30f27dd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R9

> See the error my Github Action that builds my VSCode extension : https://github.com/bywhitebird/kazam/actions/runs/6483646531/job/17608453201#step:5:218

**Steps to Reproduce**

Use `vscode-uri>=3.0.8`.

**Solutions**

I managed to build my VSCode extension with this code:
```js
build.onResolve({ filter: /^(vscode-.*|estree-walker|jsonc-parser)/ }, (args) => {
  const pathUmdMay = require.resolve(args.path, { paths: [args.resolveDir] })
  // Call twice the replace is to solve the problem of the path in Windows
  let pathEsm = pathUmdMay.replace('/umd/', '/esm/').replace('\\umd\\', '\\esm\\')

  // Try to resolve the path
  // If it fails, if the file extension is .js, try to replace it with .mjs
  try {
    require.resolve(pathEsm, { paths: [args.resolveDir] })
  }
  catch {
    if (pathEsm.endsWith('.js'))
      pathEsm = pathEsm.replace(/\.js$/, '.mjs')
  }

  return { path: pathEsm }
})
```

This code tries to resolve the new path. If it fails, it tries to resolve the import by replacing `.js` with `.mjs`.

It works, but I think it is still not robust enough. Another solution might be considered.

**Comment by johnsoncodehk** [comment]
Thanks for the report! Thanks to @remcohaszing efforts at https://github.com/microsoft/vscode/issues/192144, some vscode packages have fixed the module format, we fixed the build script in other repo, but forgot to fix the starter repo, will update it!
