### ISSUE TITLE
Sample does not handle TS correctly

### ISSUE THREAD

**Issue by ejfasting** [volarjs/language-tools-starter#8]
Hi, 

Just wanted to let you know that the starter-sample does not handle TS:
![image](https://github.com/volarjs/starter/assets/60758190/c2a05695-5f6f-42ec-9878-947129031c45)

The issue seems to be that typescript does not 'know' the file-extension. Breakpoint inside typescript.js:
![image](https://github.com/volarjs/starter/assets/60758190/1a63815d-5eba-42ee-a64c-6684b96b5a31)
message: 'File .../starter/sample/test.html1 has unknown extension.' 

The Readme.md does not say it supports TS either, probably a good idea to update it :)

//E

**Comment by johnsoncodehk** [comment]
I just updated the sample to support both TS+JS. The error in typescript.js is an internal error of TS and you can ignore it.
